import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Logo from "../assets/logohome.png";
import Banner from "../assets/banner.png";
import Jesus from "../assets/jesus.png";
import Book from "../assets/book.png";
import Hymns from "../assets/hymns.png";
import LandingInfo from "../components/LandingInfo";
import Face from "../assets/face.png";
import Whats from "../assets/whats.png";
import Inst from "../assets/inst.png";

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-full">
        <div className="relative h-4/5 ">
          <Image
            src={Banner}
            className="absolute object-cover z-[-1] pointer-events-none  select-none"
            layout="fill"
          />
          <div
            className="absolute w-full h-full  z-[-1] flex items-center  pointer-events-none "
            style={{
              background:
                "linear-gradient(102.7deg, #000000 0%, rgba(0, 0, 0, 0) 67.73%, rgba(0, 0, 0, 0) 100.81%)",
            }}
          >
            <div className="container text-white font-bold mx-auto manrope text-[64px] px-12">
              <div className="text-[18px] mb-2 text-[#FF7D00]">
                JAS SANO 2022 - Santa Cruz
              </div>
              <div className="text-white leading-[70px]">“Mi Casa y yo</div>
              <div> Serviremos al Señor”</div>
              <div className="mt-4 font-light text-[32px]"> Josue 24:15</div>
            </div>
          </div>
          <div className=" absolute w-full">
            <header className="h-28 w-full flex container mx-auto justify-between items-center">
              <div>
                <Image src={Logo} />
              </div>
              <div className="flex gap-8 items-center text-white">
                <div>Conoce mas</div>
                <div>Normas</div>
                <div>Donde va a ser?</div>
                <button className="bg-[#FF7D00] px-[24px] text-black rounded-xl py-[12px]">
                  Inscribete
                </button>
              </div>
            </header>
          </div>
        </div>
        <main className="container mx-auto pt-16">
          <LandingInfo
            title="Tema"
            description='"Mi casa y yo serviremos al señor”'
            linkText="Servir"
            link="www.google.com"
            image={Jesus}
          />
          <div className="h-20" />
          <LandingInfo
            title="Lema"
            description="Josue 24:15"
            linkText="Leer el lema"
            link="www.google.com"
            reverse
            image={Book}
          />
          <div className="h-20" />
          <LandingInfo
            title="Himno"
            description="#154 Haz tu lo justo"
            linkText="Leer el himno"
            link="www.google.com"
            image={Hymns}
          />
          {/* <div className="mt-36">
            <h2 className="font-[600] text-[36px]">Testimonios</h2>
            <div></div>
          </div> */}
        </main>
        <footer className="bg-[#E9E9E9] h-64 mt-[100px] flex justify-center items-center">
          <div>
            <div className="flex items-center gap-6 justify-center mb-5">
              <a href="facebook.com">
                <Image src={Face} />
              </a>
              <a href="whatsapp.com">
                <Image src={Whats} />
              </a>
              <a href="instagram.com">
                <Image src={Inst} />
              </a>
            </div>
            <div className="text-[20px]">Nuestras redes sociales</div>
          </div>
        </footer>
      </div>
    </>
  );
};
export default Home;
